### ISSUE TITLE
Neues Startprojekt

### ISSUE THREAD

**Issue by perdix** [grisu48/SEPM-SS12-Project#10]
Unser Projekt ist kein Java Project, sondern ein Web Application Project. Die können erstellt werden, wenn das GWT-Plugin installiert wurde. Wenn man dann ein neues Web Application Project erstellt, wird ein kleines Beispielprogramm dargestellt. Das eignet sich ganz gut zum Weitermachen, weil es auch eine Beispiel für asynchrone Kommunikation beinhaltet.

Ich würde ganz gerne schon ein bisschen mit GWT arbeiten, dazu brauchen wir aber eben so ein Web Application Project zum Starten. Felix kannst du so eines erstellen und dann als neuen Master Branch pushen. Sozusagen als Startschuss?
Was meinst du ihr dazu?

**Comment by grisu48** [comment]
## Mach ich, wenn ich wieder in IBK bin.

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

perdix reply@reply.github.com wrote:

Unser Projekt ist kein Java Project, sondern ein Web Application Project. Die können erstellt werden, wenn das GWT-Plugin installiert wurde. Wenn man dann ein neues Web Application Project erstellt, wird ein kleines Beispielprogramm dargestellt. Das eignet sich ganz gut zum Weitermachen, weil es auch eine Beispiel für asynchrone Kommunikation beinhaltet.

Ich würde ganz gerne schon ein bisschen mit GWT arbeiten, dazu brauchen wir aber eben so ein Web Application Project zum Starten. Felix kannst du so eines erstellen und dann als neuen Master Branch pushen. Sozusagen als Startschuss?
Was meinst du ihr dazu?

---

Reply to this email directly or view it on GitHub:
https://github.com/grisu48/SEPM-SS12-Project/issues/10
