### ISSUE TITLE
Testdrehbuch

### ISSUE THREAD

**Issue by perdix** [grisu48/SEPM-SS12-Project#12]
Wir brauchen ein Testdrehbuch mit:
Entwicklertests (JUnit) - betrifft wahrscheinlich am ehesten @grisu48
Abnahmetest (Ablauftests) - da sollten wir uns gemeinsam ein paar ausdenken @theoneone, @perdix

**Comment by the-littlelion** [comment]
In der VO ist das Testdrehbuch so erklärt worden, dass das mit dem Kunden bei der Abnahme durchgearbeitet werden soll. Unit-Tests gehören da nicht dazu - die sollen außerhalb des Drehbuchs durchgeführt werden.

Wie seht Ihr das?

**Comment by grisu48** [comment]
Can we close that issue?

**Comment by perdix** [comment]
das stimmt, das drehbuch enthält offiziell nur die kundentest. trotzdem finde ich es sinnvoll, alle test gemeinsam zu dokumentieren.da bietet sich das testheft an. wenn ihr das beide anderes sieht, lass ich mich aber gerne überzeugen...

**Comment by grisu48** [comment]
OK, aber momentan kommen die Tests eher als letzteres dran ... Solange GWT zickt, gibt's wichtigere ;-)

**Comment by perdix** [comment]
Ja, ich sags nur unter der Hand, aber die Tests sind Goodies, solange wir keine lauffähige Version haben :)

**Comment by grisu48** [comment]
Och, würd' ich so gar net stehen lassen - Das Konzept der agilen Programmierung, das die Weber am Freitag vorgestellt hat, wirkt überzeugend und hat mich total motiviert!
