### ISSUE TITLE
DB-Modell

### ISSUE THREAD

**Issue by the-littlelion** [grisu48/SEPM-SS12-Project#13]
Datenbankmodell:
E/R-Modell und Datenbank aufsetzen

**Comment by grisu48** [comment]
Es gibt ein Update in der Dropbox!
Das alte PNG bitte als hinfällig betrachten, es haben ein paar Attribute gefehlt:
- RealName in User
- EMail in User
- message im Comment

@theoneone: Ist es möglich, die DB-Objekte schon mal als Klassen zu implementieren? Würde bei der Test-Persistenzschicht schön aussehen, da wir die dann für die JUnit-Tests behalten könnten.
