### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by grisu48** [grisu48/SEPM-SS12-Project#16]
Create a sequence diagram (Information flow from GUI to application and vice versa)

Squence diagram must show how the information flows, it must not be complete but show clearly how the flow is

**Comment by grisu48** [comment]
NOTE: Java breadcrumbs may be a help

**Comment by the-littlelion** [comment]
Assignement changed to @theoneone 
Two examples e.g. for a User and a Snippet relevant case.
