### ISSUE TITLE
Hibernate code

### ISSUE THREAD

**Issue by the-littlelion** [grisu48/SEPM-SS12-Project#19]
Persistenzklassen implementiern

**Comment by grisu48** [comment]
You receive the description of the needed entity object within this week.

**Comment by the-littlelion** [comment]
@grisu48 @perdix
Getting Started Guide: http://docs.jboss.org/hibernate/orm/4.1/quickstart/en-US/html/

@grisu48 Cache: Kap. 21.2:
Hibernate Core Reference Manual: http://docs.jboss.org/hibernate/orm/4.1/manual/en-US/html/
