### ISSUE TITLE
GWT: Server <-> Client comm

### ISSUE THREAD

**Issue by grisu48** [grisu48/SEPM-SS12-Project#23]
Work with remote procedure call, and bring up the communication between the server and the cliennt

**Comment by grisu48** [comment]
Subissue 1 done: Async Callback Interfaces :-)
Thanks, @perdix

**Comment by perdix** [comment]
Waiting for Implementations :)

**Comment by grisu48** [comment]
Yeah, having some little problems with the Session Cookie managmenet and the servlets, I'll fix that! :-)

**Comment by grisu48** [comment]
The communication is implemented, i have to test it, but now RPC looks pretty good
