### ISSUE TITLE
Use-Case-Diagramme

### ISSUE THREAD

**Issue by perdix** [grisu48/SEPM-SS12-Project#4]

**Comment by perdix** [comment]
@grisu48 @theoneone @perdix

**Comment by grisu48** [comment]
Das erste Konzept der Use-Case Diagramme ist online (Dropbox)

**Comment by grisu48** [comment]
@theoneone hat in der Dropbox das UseCase hochgeladen. Meinen Segen hat es, von mir aus können wir das so lassen.
@perdix @theoneone - Was meint Ihr?

**Comment by perdix** [comment]
Passt!

**Comment by perdix** [comment]
Wow, das PDF zu den Use-Cases ist einfach der Hammer!

**Comment by the-littlelion** [comment]
Das upgedatete Diagramm ist in der Dropbox:

2 Versionen:
Full version - mit 2.Iteration und Kommentaren
Abgespeckte Version - 1. Iteration als *.png

**Comment by the-littlelion** [comment]
@perdix @grisu48 @theoneone

Habe das Diagramm nochmal überarbeitet und hochgeladen. Ein Case war doppelt.
Die Kurzbeschreibung ist auch online.
Heute hat Ruth in der VO gesagt, dass das gesamte Usecase-Diagramm im Pflichtenheft sein sollte. Allerdings ist im Beschreibungstext zu unterscheiden, was sofort implementiert wird - hier müssen ausführliche Beschreibungen rein - und was später kommt - hier reicht eine Kurzbeschreibung mit dem Vermerk '2. Iteration'.

Sei wie es sei, ich schaffe zeitgerecht nur die Minimalversion, wie besprochen.

**Comment by the-littlelion** [comment]
Ich brauche etwas Hilfe bei der Zuordnung "Involvierte Klassen" in der Langbeschreibung der Uscases.

Könnt Ihr mir da weiterhelfen?

**Comment by grisu48** [comment]
Involvierte Klassen wären die Klassen aus fachlicher Sicht, right?

**Comment by the-littlelion** [comment]
@grisu48 
Ja.
Es sind die Fachklassen, die im jew. Usecase gebraucht werden (lesend, schreibend oder erzeugend)

**Comment by the-littlelion** [comment]
Usecases fertig gezeichnet und kommentiert
