### ISSUE TITLE
Create Editable Label and EditableHTML

### ISSUE THREAD

**Issue by perdix** [grisu48/SEPM-SS12-Project#45]
As soon as possible GWTbook needed...

**Comment by grisu48** [comment]
Editable Label for the issue of the Snippet data is kind of useless - Its too small and too complicated for this data.

I recomment to edit the whole snippet in a sperated popup windows, and give another, also distincted popupwindow extra for viewing the full code.

See my code examples in the GUI

**Comment by perdix** [comment]
i'll have look, also hought about that.. 
i just wanted to avoid too many popups, normaly a user doesn't like these...
