### ISSUE TITLE
Pflichtenheft

### ISSUE THREAD

**Issue by perdix** [grisu48/SEPM-SS12-Project#7]

**Comment by perdix** [comment]
Könnt ihr, wenn ihr Zeit habt, einen kurze Beschreibung zu den Use-Cases bzw. zum Klassendiagramm schreiben?
Ich übernehme den Rest! LG Paul
@theoneone, @grisu48

**Comment by grisu48** [comment]
Ich bin am Klassendiagramm.
Bis morgen sollte ich da was zusammengestellt haben un einen ersten kurzen Text dazu entworfen haben.
Übernehme ich.

**Comment by perdix** [comment]
Erste Einleitung fertig, schaut mal..

**Comment by the-littlelion** [comment]
Bin mit dem Einfügen der Usecase Texte noch nicht fertig.
Werde sie noch heute fertigstellen und morgen früh hochladen.

**Comment by the-littlelion** [comment]
Usecases sind jetzt fertig
