### ISSUE TITLE
Oberflächenprototyp

### ISSUE THREAD

**Issue by grisu48** [grisu48/SEPM-SS12-Project#9]
Den Prototypen der Oberfläche designen (Konzept erstellen)
Die Implementierung erfolgt erst im Milestone 2!

**Comment by grisu48** [comment]
Paul, ich habe dich mal an dieses Ticket gebunden. Natürlich unterstützte ich dich dabei.
Was haltet ihr von meinen ersten Zeitplan? Ist Milestone 1 (Fertigstellung des Konzepts und der Planung) bis nächsten Monatg erreichbar?

**Comment by perdix** [comment]
Ja, das ist mein nächster Programmpunkt :)

**Comment by perdix** [comment]
Aber bis nächste Woche ist das äußerst unwahrscheinlich. Ich muss mich dafür erst in GWT einarbeiten. Aber man kann ja nächste Woche die Wireframes herzeigen.

**Comment by grisu48** [comment]
## Jo, mit Konzept meinte ich ja die Wireframes! In einer woche sich in gwt einarbeiten ist im besten falle ... Optimistisch ... ;-)

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

perdix reply@reply.github.com wrote:

Aber bis nächste Woche ist das äußerst unwahrscheinlich. Ich muss mich dafür erst in GWT einarbeiten. Aber man kann ja nächste Woche die Wireframes herzeigen.

---

**Comment by perdix** [comment]
ja, dann, schau mal in den Dropbox-Ordner!

**Comment by grisu48** [comment]
## Jep, ich schau nochmal 'drüber und dann: "Issue closed" ;-)))

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

perdix reply@reply.github.com wrote:

ja, dann, schau mal in den Dropbox-Ordner!

---
